### ISSUE TITLE
Teku DAS misses slots

### ISSUE THREAD

**Issue by zilm13** [Nashatyrev/artemis#66]
Teku lags to produce blocks in time, see orphaned statistics: https://dora.peerdas-devnet-1.ethpandaops.io/slots/filtered?f&d=1+2+3+4+5+6+7+8+9+10+11&f.missing=1&f.orphaned=2&c=50
![2024-06-28 22 55 52](https://github.com/Nashatyrev/teku/assets/6196452/f38c7f65-ecc3-4e4e-904e-1f3c20efd070)
Clearly visible something that looks like "CPU leaking" and comb on epoch transition. During hours with low CPU usage there are no issues.
There are a lot of errors like this in logs, which is expected when we miss onSlot ticks:
```
2024-06-26 18:38:18.002 ERROR - [31mValidator   *** Failed to produce attestation  Slot: 8833 Validator: a56a236[0m
java.lang.IllegalArgumentException: Cannot create attestation for future slot. Requested 8833 but current slot is 8832
at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.createAttestationData(ValidatorApiHandler.java:398) ~[teku-beacon-validator-develop.jar:UNKNOWN+g3768eca]
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
at tech.pegasys.teku.infrastructure.events.DirectEventDeliverer.executeMethod(DirectEventDeliverer.java:74) ~[teku-infrastructure-events-develop.jar:UNKNOWN+g3768eca]
at tech.pegasys.teku.infrastructure.events.DirectEventDeliverer.deliverToWithResponse(DirectEventDeliverer.java:67) ~[teku-infrastructure-events-develop.jar:UNKNOWN+g3768eca]
at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer.lambda$deliverToWithResponse$1(AsyncEventDeliverer.java:80) ~[teku-infrastructure-events-develop.jar:UNKNOWN+g3768eca]
at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer$QueueReader.deliverNextEvent(AsyncEventDeliverer.java:125) ~[teku-infrastructure-events-develop.jar:UNKNOWN+g3768eca]
at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer$QueueReader.run(AsyncEventDeliverer.java:116) ~[teku-infrastructure-events-develop.jar:UNKNOWN+g3768eca]
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
at java.base/java.lang.Thread.run(Unknown Source) [?:?]
```
[thread_dumps.zip](https://github.com/user-attachments/files/16036755/thread_dumps.zip)

**Comment by zilm13** [comment]
resolved with #70
