### ISSUE TITLE
Teku failed to sync completely with established network

### ISSUE THREAD

**Issue by zilm13** [Nashatyrev/artemis#73]
Reached slot 13131 but no more
```
INFO  - [nyota] SimpleSidecarRetriever.nextRound: completed: 461, errored: 0,  total pending: 819, active pending: 819, new pending: 0, number of custody peers: 128 cols: 3+ peers
...
 ERROR - Unexpected rejected execution due to full task queue in storage_query-async-19
ERROR - Failed to check for sync stalls
java.util.concurrent.RejectedExecutionException: Rejected execution on task queue - beaconchain
at tech.pegasys.teku.infrastructure.async.MetricTrackingExecutorFactory.onRejectedExecution(MetricTrackingExecutorFactory.java:116) ~[teku-infrastructure-async-develop.jar:UNKNOWN+ge8d5fba]
at tech.pegasys.teku.infrastructure.async.MetricTrackingExecutorFactory.lambda$newCachedThreadPool$0(MetricTrackingExecutorFactory.java:94) ~[teku-infrastructure-async-develop.jar:UNKNOWN+ge8d5fba]
at java.base/java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source) ~[?:?]
at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$runAfterDelay$0(ScheduledExecutorAsyncRunner.java:93) ~[teku-infrastructure-async-develop.jar:UNKNOWN+ge8d5fba]
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
at java.base/java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by Nashatyrev** [comment]
Probably the duplicate of #108
